"""init tables

Revision ID: b7cfe518b75c
Revises: 
Create Date: 2025-11-17 05:01:18.991416

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7cfe518b75c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tasks',

        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('task_type', sa.Enum('TASK', 'JOB', name='tasktype'), nullable=False),
        sa.Column('kind', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('status', sa.Enum('SCHEDULED', 'RUNNING', 'SUCCESS', 'FAILED', 'SKIPPED', name='status'),
                  nullable=False),
        sa.Column('error', sa.String(), nullable=True),
        sa.Column('parent_id', sa.Uuid(), nullable=True),
        sa.Column('input', sa.JSON(), nullable=True),
        sa.Column('output', sa.JSON(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                  nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_kind'), 'tasks', ['kind'], unique=False)
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_table('task_dependencies',
                    sa.Column('task_id', sa.Uuid(), nullable=False),
                    sa.Column('upstream_task_id', sa.Uuid(), nullable=False),
                    sa.Column('job_id', sa.Uuid(), nullable=True),
                    sa.Column('merge_strategy', sa.String(length=20), nullable=False),
                    sa.Column('mapper_config', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['tasks.id'], ),
                    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
                    sa.ForeignKeyConstraint(['upstream_task_id'], ['tasks.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_task_dependencies_job_id'), 'task_dependencies', ['job_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_upstream_task_id'), 'task_dependencies', ['upstream_task_id'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_dependencies_upstream_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_job_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_kind'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
